/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicTacToeRouteImport } from './routes/tic-tac-toe'

const TicTacToeRoute = TicTacToeRouteImport.update({
  id: '/tic-tac-toe',
  path: '/tic-tac-toe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/tic-tac-toe': typeof TicTacToeRoute
}
export interface FileRoutesByTo {
  '/tic-tac-toe': typeof TicTacToeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/tic-tac-toe': typeof TicTacToeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/tic-tac-toe'
  fileRoutesByTo: FileRoutesByTo
  to: '/tic-tac-toe'
  id: '__root__' | '/tic-tac-toe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TicTacToeRoute: typeof TicTacToeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tic-tac-toe': {
      id: '/tic-tac-toe'
      path: '/tic-tac-toe'
      fullPath: '/tic-tac-toe'
      preLoaderRoute: typeof TicTacToeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  TicTacToeRoute: TicTacToeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
